[project]
name = "hexlet-code"
version = "0.1.0"
description = "It's tool to compare two configuration files and show differences."
authors = [
    { name = "vlrkors", email = "vlrkors@gmail.com" }
]
readme = "README.md"
requires-python = ">=3.12"
dependencies = []
