name: Python CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # важно для анализаторов веток (например, PR)

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install uv
        run: |
          pip install uv
          # Проверяем, что uv доступен
          uv --version

      - name: Install dependencies
        run: |
          uv pip install --system -e ".[dev]"

      - name: Run linter and pytest
        run: |
          make check

      - name: Run test coverage
        run: |
          make test-coverage

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=python-project-50
            -Dsonar.organization=vlrkors
            -Dsonar.sources=.
            -Dsonar.python.coverage.reportPaths=coverage.xml
            -Dsonar.host.url=https://sonarcloud.io