name: Python CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"
    
    - name: Install uv
      run: pip install uv
    
    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.cache/pip
          ~/.cache/uv
        key: ${{ runner.os }}-deps-${{ hashFiles('**/pyproject.toml') }}
    
    - name: Install dependencies
      run: |
        uv pip install -e ".[dev]"
    
    - name: Run linter
      run: |
        uv run ruff check gendiff tests
        uv run black --check gendiff tests

  test:
    needs: lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"
    
    - name: Install uv
      run: pip install uv
    
    - name: Cache dependencies
      uses: actions/cache@v3
      id: cache
      with:
        path: |
          ~/.cache/pip
          ~/.cache/uv
        key: ${{ runner.os }}-deps-${{ hashFiles('**/pyproject.toml') }}
    
    - name: Install dependencies
      run: |
        uv pip install -e ".[dev]"
        uv pip install pytest-cov
    
    - name: Run tests
      run: |
        uv run pytest tests/ -v
    
    - name: Generate coverage
      run: |
        uv run pytest --cov=gendiff --cov-report=xml tests/

  sonarcloud:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"
    
    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.cache/pip
          ~/.cache/uv
        key: ${{ runner.os }}-deps-${{ hashFiles('**/pyproject.toml') }}
    
    - name: Install dependencies
      run: |
        uv pip install -e ".[dev]"
        uv pip install pytest-cov
    
    - name: Run SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@v4.1.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      with:
        args: >
          -Dsonar.projectKey=python-project-50
          -Dsonar.organization=vlrkors
          -Dsonar.python.coverage.reportPaths=coverage.xml
          -Dsonar.sources=gendiff
          -Dsonar.cpd.exclusions=**/tests/**