name: Python CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"
    
    - name: Install uv with pipx (recommended)
      run: |
        python -m pip install --user pipx
        python -m pipx ensurepath
        pipx install uv
    
    - name: Install dependencies
      run: |
        uv pip install -e ".[dev]"
    
    - name: Run linter
      run: |
        uv run ruff check gendiff tests
    
    - name: Run tests with coverage
      run: |
        uv pip install pytest-cov
        uv run pytest --cov=gendiff --cov-report=xml tests/
    
    - name: Upload coverage to SonarCloud
      uses: SonarSource/sonarcloud-github-action@master 
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      with:
        args: >
          -Dsonar.projectKey=python-project-50
          -Dsonar.organization=vlrkors
          -Dsonar.python.coverage.reportPaths=coverage.xml
          -Dsonar.sources=gendiff